api_platform:
  title: Pensum API
  version: 1.0.0
  defaults:
    stateless: true
    cache_headers:
      vary: [ 'Content-Type', 'Authorization', 'Origin' ]
  formats:
    jsonld:
      mime_types: [ 'application/ld+json' ]
    json:
      mime_types: [ 'application/json' ]
    html:
      mime_types: [ 'text/html' ]
  enable_docs: true
  enable_entrypoint: true
  enable_swagger_ui: true
  enable_swagger: true
  eager_loading:
    max_joins: 300
  swagger:
    api_keys:
      bearerAuth: # this name is arbitrary
        name: Authorization
        type: header