lexik_jwt_authentication:
  secret_key: '%env(resolve:JWT_SECRET_KEY)%'
  public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
  pass_phrase: '%env(JWT_PASSPHRASE)%'
  api_platform:
    check_path: /login_check
    username_path: email
    password_path: security.credentials.password
  token_extractors:
    authorization_header:
      enabled: true       # turn header‐based auth back on
      prefix: Bearer     # match “Bearer <token>”
      name: Authorization
    cookie:
      enabled: false      # we’re not using cookie extraction
    query_parameter:
      enabled: false      # or URL param